# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

workspace = "MicroAppExample.xcworkspace"
project = "MicroAppExample.xcodeproj"
scheme = "MicroAppExample"
pgyer_api_key = ENV['PGYER_API_KEY']
pgyer_user_key = ENV['PGYER_USER_KEY']

default_platform(:ios)

platform :ios do
  desc "Build project"
  lane :build_ipa do |options|
    configuration = options[:configuration] ? options[:configuration] : "Release"
    cocoapods
    build_app(
      workspace: workspace,
      configuration: configuration,
      scheme: scheme,
      silent: true,
      clean: true,
      output_directory: "build",
      export_method: "development",
    )
    ipa_path = lane_context[SharedValues::IPA_OUTPUT_PATH]
    pgyer(
      api_key: pgyer_api_key,
      user_key: pgyer_user_key,
      ipa: ipa_path,
    )


    version = get_version_number(
      xcodeproj: project,
    )

    build_number = get_build_number(
      xcodeproj: project,
    )

    increment_build_number(
      xcodeproj: project,
    )

    git_add
    git_commit(
      path: "."
      message: "release #{version}(#{build_number})"
    )
    add_git_tag(
      tag: "#{version}(#{build_number})"
    )
    push_to_git_remote(
      local_branch: "main",
      remote_branch: "main",
      tags: true,
    )
  end
end
